[workspace]

members = [
    "boards/*",
    "examples/*",
    "libraries/*"
]

[workspace.dependencies.atsamd-hal]
version = "0.15.1"
features = ["same51j", "same51j-rt", "dma"]

[workspace.dependencies.serde]
version = "1.0.150"
default-features = false
features = ["derive"]

[workspace.dependencies.cortex-m]
version = "0.7.6"
features = ["critical-section-single-core"]

[workspace.dependencies.mavlink]
git = "https://github.com/uorocketry/rust-mavlink"
branch = "hydra_dialect"
features = ["embedded", "uorocketry"]
default-features = false

[profile.dev]
# Using LTO causes issues with GDB
lto = false

# Only optimize dependencies for size in debug, keeping the top crate debug friendly
# [profile.dev.package."*"]
# opt-level = "s"

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true
lto = true
opt-level = "s"