# Configuration for cargo-embed. This command can be used to flash and start a gdb-server.

[v2.general]
chip = "STM32H733VGTx"

[v2.probe]
protocol = "Swd"

[v2.gdb]
enabled = true

[default.general]
chip = "STM32H733VGTx"

[default.probe]
protocol = "Swd"

[default.gdb]
enabled = true
