[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

# -----------------------
# Typescript Bindings
# -----------------------
[tasks.generate-ts-bindings]
command = "cargo"
args = ["test", "-p", "messages", "--no-default-features", "--features", "ts", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}"]

# -----------------------
# Host Testing
# -----------------------

[tasks.test-host]
dependencies = [
    "test-messages",
]

[tasks.test-messages]
command = "cargo"
args = ["test", "-p", "messages", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}", "--features", "std", "--no-default-features"]

# -----------------------
# Embedded Testing
# -----------------------

[tasks.test-device]
dependencies = [
    "test-common-arm",
]

[tasks.test-common-arm]
command = "cargo"
args = ["test", "-p", "common-arm-test", "${@}"]
