# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.140.1/containers/cpp/.devcontainer/base.Dockerfile

FROM ubuntu:latest

# [Optional] Uncomment this section to install additional packages.
RUN apt-get update && apt-get -y install --no-install-recommends cmake ninja-build gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib
