# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.140.1/containers/cpp/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/vscode/devcontainers/cpp:ubuntu-20.04

# [Optional] Uncomment this section to install additional packages.
RUN apt-get update && apt-get -y install --no-install-recommends gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib
