// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Air { time_stamp: number, status: number, pressure_abs: number, altitude: number, pressure_diff: number, true_airspeed: number, air_temperature: number, }