// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Log } from "./Log";
import type { Sensor } from "./Sensor";
import type { State } from "./State";

export type Data = { state: State } | { sensor: Sensor } | { log: Log };