// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EkfQuat { time_stamp: number, quaternion: Array<number>, euler_std_dev: Array<number>, status: number, }