// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GpsVel { time_stamp: number, status: number, time_of_week: number, velocity: Array<number>, velocity_acc: Array<number>, course: number, course_acc: number, }