// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Imu2 { temperature: number, delta_velocity: Array<number>, delta_angle: Array<number>, }