// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { LogLevel } from "./LogLevel";

export interface Log { level: LogLevel, event: Event, }