// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Data } from "./Data";
import type { Sender } from "./Sender";

export interface Message { timestamp: bigint, sender: Sender, data: Data, }