// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorData } from "./SensorData";

export interface Sensor { component_id: number, data: SensorData, }