// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Air } from "./Air";
import type { EkfNav1 } from "./EkfNav1";
import type { EkfNav2 } from "./EkfNav2";
import type { EkfQuat } from "./EkfQuat";
import type { GpsVel } from "./GpsVel";
import type { Imu1 } from "./Imu1";
import type { Imu2 } from "./Imu2";
import type { UtcTime } from "./UtcTime";

export type SensorData = { UtcTime: UtcTime } | { Air: Air } | { EkfQuat: EkfQuat } | { EkfNav1: EkfNav1 } | { EkfNav2: EkfNav2 } | { Imu1: Imu1 } | { Imu2: Imu2 } | { GpsVel: GpsVel };