// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UtcTime { time_stamp: number, status: number, year: number, month: number, day: number, hour: number, minute: number, second: number, nano_second: number, gps_time_of_week: number, }