on:
  push:
    branches: [ master ]
  pull_request:

name: Build

jobs:
  build:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
            # Install CMake
      - name: Install packages
        run: sudo apt update && sudo apt install -y cmake libnewlib-dev
      - name: Use correct cargo config
        run: mv .cargo/config-ci .cargo/config
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 'latest'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - uses: actions-rs/cargo@v1
        with:
          command: build
