on:
  push:
    branches: [ master ]
  pull_request:

name: Build

jobs:
  build:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - uses: actions-rs/cargo@v1
        with:
          command: build
