on:
  push:
    branches: [ master ]
  pull_request:

name: Build

jobs:
  build:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt update && sudo apt install -y cmake libnewlib-dev
      - name: Use correct cargo config
        run: mv .cargo/config-ci .cargo/config
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.2.Rel1'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        name: "Build all binaries"
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: "Check that tests compile"
        with:
          command: test -p common-arm-test --no-run
