on: pull_request

name: Linter

jobs:
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: sudo apt update && sudo apt install -y cmake libnewlib-dev
      - name: Use correct cargo config
        run: mv .cargo/config-ci .cargo/config
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.2.Rel1'
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          target: thumbv7em-none-eabihf
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
